apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/cleanup
spec:
  project: default
  source:
    repoURL: https://github.com/Atom-oh/AWS-Demo-Platform
    targetRevision: main
    path: k8s/system/actions-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
