apiVersion: v1
kind: ConfigMap
metadata:
  name: atlantis-config
  namespace: atlantis
data:
  repos.yaml: |
    repos:
      - id: github.com/Atom-oh/AWS-Demo-Platform
        workflow: standard
        allowed_overrides: [workflow, apply_requirements]
        apply_requirements: [approved, mergeable]
        delete_source_branch_on_merge: false
      - id: github.com/Atom-oh/multi-region-architecture
        workflow: standard
        allowed_overrides: [workflow, apply_requirements]
        apply_requirements: [approved, mergeable]
        delete_source_branch_on_merge: false

    workflows:
      standard:
        plan:
          steps:
            - init
            - plan
        apply:
          steps:
            - apply
