apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atlantis-github-app
  namespace: atlantis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: atlantis-github-app
    creationPolicy: Owner
  data:
    - secretKey: app-id
      remoteRef: { key: /demo-platform/atlantis/github-app-id }
    - secretKey: installation-id
      remoteRef: { key: /demo-platform/atlantis/github-app-installation-id }
    - secretKey: private-key
      remoteRef: { key: /demo-platform/atlantis/github-app-private-key }
    - secretKey: webhook-secret
      remoteRef: { key: /demo-platform/atlantis/github-webhook-secret }
